# This workflow will do a complete formatting as per the prettier config and make the necessary changes.

on:
  push:
    branches: [ master ]

name: Node Code Formatter

jobs:
  lint:
    name: Node Code Formatter
    runs-on: ubuntu-latest
    steps:
    - name: Node Code Formatter
      uses: MarvinJWendt/run-node-formatter@stable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}